version: '2'
services:
  reverse_proxy:
    build: ./nginx
    links:
      - node:nginx_backend
    environment:
      - NGINX_BACKEND_PORT=3000
    expose:
      - "80"
    volumes_from:
      - node
  node:
    build: ../../
    environment:
      - ENV=development
    expose:
      - "3000"
    restart: always
